---
title: "Hotel Data Scraping"
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
    number_sections: true
    theme: united
    highlight: espresso
    df_print: paged
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  fig.align = "center",
  class.output = ".scroll-500",
  comment = "#>"
)
options(scipen = 9999)
options(warn = -1) # remove warning messages
```

# __Library Setup__

```{r}
library(tidyverse)
library(rvest)
library(stringr)
library(rlist)
```

# __Hotel Data Scraping__

Scraping Function
```{r}
scrap_htl <- function(name){
  # Iniate list for final output
  Name <- list()
  Description <- list()
  Star <- list()
  Long <- list()
  Lat <- list()
  
  # Initiate General Form of Hotel Link (Source : Booking.com)
  link_start <- paste0("https://www.booking.com/hotel/id/")
  link_end <- paste0(".en-gb.html")
  
  # Scrape the data
  for (i in 1: length(name)){
    # Define the link
    link <- paste0(link_start, name[i], link_end)
    
    # Reading HTML Code from the website
    web <- read_html(link)
    
    # Specifying class of the data
    ## Name
    name_html <- html_node(web,".hp__hotel-name")
    ## Description
    desc_html <- html_node(web,"#property_description_content")
    ## Star
    star_html <- html_node(web,".bui-rating.bui-rating--smaller")
    ## Latitude, Longitude
    lglat_html <- html_node(web, ".jq_tooltip.loc_block_link_underline_fix.bui-link")
    
    # Converting the data to text
    ## Name
    name_data <- html_text(name_html, trim = TRUE)
    name_data <- gsub(".*\n","",name_data)
    ## Description
    desc_data <- html_text(desc_html, trim = TRUE)
    desc_data <- gsub("\n","",desc_data)
    ## Star
    star_data <- html_attr(star_html, "aria-label")
    star_data <- substr(star_data,1,1)
    ## Latitude, Longitude
    lglat_data <- html_attr(lglat_html, "data-atlas-latlng")
    lg_data <- sub(".*,","",lglat_data) 
    lat_data <- sub(",.*","",lglat_data)
    
    # Combine data to one list
    Name <- c(Name, name_data)
    Description <- c(Description, desc_data)
    Star <- c(Star, star_data)
    Long <- c(Long, lg_data)
    Lat <- c(Lat, lat_data)
  }
  
  # Combine data to one data frame
  Name <- Name %>% unlist()
  Description <- Description %>% unlist()
  Star <- Star %>% unlist()
  Long <- Long %>% unlist()
  Lat <- Lat %>% unlist()
  Hotel <- data.frame(
    "Name" = Name, 
    "Description" = Description,
    "Star" = Star,
    "Long" = Long,
    "Lat" = Lat)
  return(Hotel)
}
```


Use the Function to Scrap Hotel Data
```{r}
# Bali
bali_htl <- c("grandmas-hotels-legian","amnaya-resort-benoa","radisson-blu-bali-uluwatu")
bali <- scrap_htl(bali_htl)

# Yogyakarta
yogya_htl <- c("artotel-yogyakarta","grand-ambarrukmo-yogyakarta","yogyakarta-marriott")
yogya <- scrap_htl(yogya_htl)

# Makassar
mksr_htl <- c("maxonehotels-com-at-resort-delia","harper-perintis", "the-rinra")
mksr <- scrap_htl(mksr_htl)

# Malang
mlg_htl <- c("the-batu-villas","aston-inn-batu","golden-tulip-holland-resort-batu")
mlg <- scrap_htl(mlg_htl)

# Bandung
bdg_htl <- c("yello-paskal-bandung","hyatt-regency-bandung","the-trans-luxury-bandung")
bdg <- scrap_htl(bdg_htl)
```

Combine Final Output
```{r}
bl <- read.csv("Data/Bali_destination.csv")
yg <- read.csv("Data/Yogya_destination.csv")
mks <- read.csv("Data/Makassar_destination.csv")
ml <- read.csv("Data/Malang_destination.csv")
bd <- read.csv("Data/Bandung_destination.csv")

colnames(bl) <- c("Name", "Description", "Star", "Long", "Lat")
bl <- rbind(bl,bali)
write.csv(bl, "Data/Bali_destination.csv", row.names = FALSE)

colnames(yg) <- c("Name", "Description", "Star", "Long", "Lat")
yg <- rbind(yg,yogya)
write.csv(yg, "Data/Yogya_destination.csv", row.names = FALSE)

colnames(mks) <- c("Name", "Description", "Star", "Long", "Lat")
mks <- rbind(mks,mksr)
write.csv(mks, "Data/Makassar_destination.csv", row.names = FALSE)

colnames(ml) <- c("Name", "Description", "Star", "Long", "Lat")
ml <- rbind(ml,mlg)
write.csv(ml, "Data/Malang_destination.csv", row.names = FALSE)

colnames(bd) <- c("Name", "Description", "Star", "Long", "Lat")
bd <- rbind(bd,bdg)
write.csv(bd, "Data/Bandung_destination.csv", row.names = FALSE)
```


# __Hotel Review Scraping__


Bali
```{r}
# Iniate list for final output
Grandmas <- list()

# Scrape the data
for (i in seq(5,500,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com.au/Hotel_Review-g608487-d3389491-Reviews-or",i,"-Grandmas_Plus_Hotel_Legian-Legian_Kuta_District_Bali.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  grandmas_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  Grandmas <- c(Grandmas, grandmas_review)
}

Grandmas <- Grandmas %>% unlist()
```

```{r}
# Iniate list for final output
Amnaya <- list()

# Scrape the data
for (i in seq(5,395,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com/Hotel_Review-g1465999-d19270238-Reviews-or",i,"-Amnaya_Resort_Benoa-Tanjung_Benoa_Nusa_Dua_Peninsula_Bali.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  amnaya_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  Amnaya <- c(Amnaya, amnaya_review)
}

Amnaya <- Amnaya %>% unlist()
```


```{r}
# Iniate list for final output
Radisson <- list()

# Scrape the data
for (i in seq(5,500,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com.au/Hotel_Review-g8366411-d13169927-Reviews-or",i,"-Radisson_Blu_Bali_Uluwatu-Uluwatu_Bali.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  radisson_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  Radisson <- c(Radisson, radisson_review)
}

Radisson <- Radisson %>% unlist()
```

```{r}
bali <- read.csv("Data/Bali_Review.csv")
bali <- bali %>% 
  mutate("Grandmas" = Grandmas) %>% 
  mutate("Amnaya" = Amnaya) %>% 
  mutate("Radisson" = Radisson)
write.csv(bali, "Data/Bali_Review.csv", row.names = FALSE)
```


Yogyakarta

```{r}
# Iniate list for final output
Artotel <- list()

# Scrape the data
for (i in seq(5,500,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com/Hotel_Review-g294230-d13229706-Reviews-or",i,"-Artotel_Yogyakarta-Yogyakarta_Region_Java.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  artotel_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  Artotel <- c(Artotel, artotel_review)
}

Artotel <- Artotel %>% unlist() 
```

```{r}
# Iniate list for final output
Grand <- list()

# Scrape the data
for (i in seq(5,125,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com/Hotel_Review-g294230-d12526280-Reviews-or",i,"-Grand_Ambarrukmo_Hotel-Yogyakarta_Region_Java.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  grand_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  Grand <- c(Grand, grand_review)
}

Grand <- Grand %>% unlist() 
```

```{r}
# Iniate list for final output
Yogyakarta <- list()

# Scrape the data
for (i in seq(5,330,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com/Hotel_Review-g5074492-d13008958-Reviews-or",i,"-Yogyakarta_Marriott_Hotel-Depok_Sleman_District_Yogyakarta_Region_Java.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  yogyakarta_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  Yogyakarta <- c(Yogyakarta, yogyakarta_review)
}

Yogyakarta <- Yogyakarta %>% unlist()
```


```{r}
yogya <- read.csv("Data/Yogyakarta_Review.csv")
yogya <- yogya %>%
  mutate("Artotel" = Artotel) %>% 
  mutate("Grand" = Grand) %>% 
  mutate("Yogyakarta" = Yogyakarta)
write.csv(yogya, "Data/Yogyakarta_Review.csv", row.names = FALSE)
```

Malang

```{r}
# Iniate list for final output
The <- list()

# Scrape the data
for (i in seq(25,60,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com/Hotel_Review-g1237079-d4886640-Reviews-or",i,"-The_Batu_Villas-Batu_East_Java_Java.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  the_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  The <- c(The, the_review)
}

The <- The %>% unlist()
```

```{r}
# Iniate list for final output
Aston <- list()

# Scrape the data
for (i in seq(5,130,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com/Hotel_Review-g1237079-d14932735-Reviews-or",i,"-Aston_Inn_Batu-Batu_East_Java_Java.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  aston_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  Aston <- c(Aston, aston_review)
}

Aston <- Aston %>% unlist()
```

```{r}
# Iniate list for final output
Golden <- list()

# Scrape the data
for (i in seq(30,215,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com/Hotel_Review-g1237079-d12441074-Reviews-or",i,"-Golden_Tulip_Holland_Resort_Batu-Batu_East_Java_Java.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  golden_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  Golden <- c(Golden, golden_review)
}

Golden <- Golden %>% unlist()
```

```{r}
malang <- read.csv("Data/Malang_Review.csv")
malang <- malang %>%
  mutate("The" = The) %>% 
  mutate("Aston" = Aston) %>% 
  mutate("Golden" = Golden)
write.csv(malang, "Data/Malang_Review.csv", row.names = FALSE)
```

Makassar

```{r}
# Iniate list for final output
MaxOneHotels <- list()

# Scrape the data
for (i in seq(5,500,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com/Hotel_Review-g297720-d10054230-Reviews-or",i,"-MaxOneHotels_Resort_Makassar-Makassar_South_Sulawesi_Sulawesi.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  maxonehotels_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  MaxOneHotels <- c(MaxOneHotels, maxonehotels_review)
}

MaxOneHotels <- MaxOneHotels %>% unlist()
```

```{r}
# Iniate list for final output
Harper <- list()

# Scrape the data
for (i in seq(5,500,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com/Hotel_Review-g297720-d10627713-Reviews-or",i,"-Harper_Perintis_Makassar-Makassar_South_Sulawesi_Sulawesi.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  harper_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  Harper <- c(Harper, harper_review)
}

Harper <- Harper %>% unlist()
```

```{r}
# Iniate list for final output
Rinra <- list()

# Scrape the data
for (i in seq(5,500,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com/Hotel_Review-g297720-d10148712-Reviews-or",i,"-The_Rinra_Makassar-Makassar_South_Sulawesi_Sulawesi.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  rinra_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  Rinra <- c(Rinra, rinra_review)
}

Rinra <- Rinra %>% unlist()
```

```{r}
makassar <- read.csv("Data/Makassar_Review.csv")
makassar <- makassar %>%
  mutate("MaxOneHotels" = MaxOneHotels) %>% 
  mutate("Harper" = Harper) %>% 
  mutate("Rinra" = Rinra)
write.csv(makassar, "Data/Makassar_Review.csv", row.names = FALSE)
```

Bandung

```{r}
# Iniate list for final output
YELLO <- list()

# Scrape the data
for (i in seq(5,500,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com/Hotel_Review-g297704-d13990373-Reviews-or",i,"-YELLO_Hotel_Paskal-Bandung_West_Java_Java.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  YELLO_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  YELLO <- c(YELLO, YELLO_review)
}

YELLO <- YELLO %>% unlist()
```

```{r}
# Iniate list for final output
Aryaduta <- list()

# Scrape the data
for (i in seq(5,500,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com/Hotel_Review-g297704-d307171-Reviews-or",i,"-Aryaduta_Bandung-Bandung_West_Java_Java.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  aryaduta_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  Aryaduta <- c(Aryaduta, aryaduta_review)
}

Aryaduta <- Aryaduta %>% unlist()
```

```{r}
# Iniate list for final output
Trans <- list()

# Scrape the data
for (i in seq(5,500,5)) {
  
  ## Define the link
  link <- paste0("https://www.tripadvisor.com/Hotel_Review-g297704-d3226872-Reviews-or",i,"-The_Trans_Luxury_Hotel-Bandung_West_Java_Java.html#REVIEWS")
  pages <- read_html(link)
  
  ## Scrape
  trans_review <- pages %>% 
        html_nodes("q.IRsGHoPm") %>%
        html_text()
  
  ## Combine scrape result to the list
  Trans <- c(Trans, trans_review)
}

Trans <- Trans %>% unlist()
```

```{r}
bandung <- read.csv("Data/Bandung_Review.csv")
bandung <- bandung %>%
  mutate("YELLO" = YELLO) %>% 
  mutate("Aryaduta" = Aryaduta) %>% 
  mutate("Trans" = Trans)
write.csv(bandung, "Data/Bandung_Review.csv", row.names = FALSE)
```